spring.application.name=Book exchange platform
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log=classpath:db.changelog-master.yaml
auth.service.url=http://localhost:8081
spring.datasource.url=jdbc:postgresql://localhost:5432/book_exchange
spring.datasource.username=postgres
spring.datasource.password=aidar2006
